name: Generate Pacman Animation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: amirkma

      - name: Push to output branch
        run: |
          mkdir -p output
          cp pacman-contribution-graph.svg output/pacman.svg
          cp pacman-contribution-graph-dark.svg output/pacman-dark.svg
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/pacman.svg output/pacman-dark.svg
          git commit -m "Update pacman" || exit 0
          git push origin output || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
